export type PortfolioMediaItem =
  | { type: "image"; src: string }
  | { type: "video"; src: string };

// Order matches the "gallery" arrays in messages/{locale}.json under
// PortfolioPage.projects[].gallery — each entry there supplies the alt/caption
// text for the item at the same index here.
export const portfolioMedia: Record<string, PortfolioMediaItem[]> = {
  sempia: [
    { type: "video", src: "/referenzen/sempia/ad.webm" },
    { type: "image", src: "/referenzen/sempia/print/menu-1.png" },
    { type: "image", src: "/referenzen/sempia/print/wochenmenu.png" },
    { type: "image", src: "/referenzen/sempia/print/menu-2.png" },
    { type: "image", src: "/referenzen/sempia/print/tageskarte.png" },
  ],
  "hotel-sempachersee": [
    { type: "image", src: "/referenzen/hotel-sempachersee/vivace/interior-wide.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/vivace/dish.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/vivace/bar-setup.jpg" },
    { type: "video", src: "/referenzen/hotel-sempachersee/aurora/before-after.webm" },
    { type: "video", src: "/referenzen/hotel-sempachersee/lago/promo.webm" },
    { type: "image", src: "/referenzen/hotel-sempachersee/print/poster-winterlounge.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/vivace/detail.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/vivace/plants.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/print/sales-folder-01.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/print/sales-folder-03.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/print/sales-folder-05.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/print/sales-folder-07.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/lago/lago-01.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/lago/lago-02.jpg" },
    { type: "image", src: "/referenzen/hotel-sempachersee/lago/lago-03.jpg" },
    { type: "video", src: "/referenzen/hotel-sempachersee/easter-brunch-reel.mp4" },
    { type: "video", src: "/referenzen/hotel-sempachersee/eventlocation-video-ad.mp4" },
    { type: "video", src: "/referenzen/hotel-sempachersee/lago/lago-promo-2.webm" },
  ],
  "ebikon-bar": [
    { type: "video", src: "/referenzen/ebikon-bar/testvideo-instagram.mp4" },
    { type: "image", src: "/referenzen/ebikon-bar/dj-fire.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/crowd.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/action.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/bar-ambiance.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/dj-1.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/performer.jpg" },
    { type: "video", src: "/referenzen/ebikon-bar/promo.mp4" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-01.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-02.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-03.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-04.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-05.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-06.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-07.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-08.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-09.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-10.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-11.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-12.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-13.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-14.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-15.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-16.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-17.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-18.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-19.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-20.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-21.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-22.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-23.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-24.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-25.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-26.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-27.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-28.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-29.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-30.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-31.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-32.jpg" },
    { type: "image", src: "/referenzen/ebikon-bar/guest-33.jpg" },
  ],
};

export const portfolioCover: Record<string, string> = {
  sempia: "/referenzen/sempia/print/menu-1.png",
  "hotel-sempachersee": "/referenzen/hotel-sempachersee/vivace/interior-wide.jpg",
  "ebikon-bar": "/referenzen/ebikon-bar/dj-fire.jpg",
};
